#!/bin/bash
echo "🚀 Mở HEART Technology Park - Trang About"
echo "======================================="
open "/Users/thuyloan0209/Documents/Test_WEBSITE_2025.06.18/about.html"
echo "✅ Đã mở web browser!"
echo ""
echo "🎯 Bạn sẽ thấy:"
echo "   - Tòa nhà màu xanh với tiêu đề 'HEART TECHNOLOGY'"
echo "   - Building tự động scroll theo nội dung (50% tốc độ)"
echo "   - Hiệu ứng parallax mượt mà"
echo "   - 7 tầng với 4 cửa sổ mỗi tầng"
echo "   - Không có xoay - tòa nhà thẳng"