#!/bin/bash
echo "🎯 Testing updated power grid animation..."
echo "📂 Opening facilities.html..."
open "file:///Users/thuyloan0209/Documents/Test_WEBSITE_2025.06.18/facilities.html"
echo "✅ Browser opened!"
echo ""
echo "🔍 What to check:"
echo "1. Navigate to '500kV Onsite Power Grid' section"
echo "2. Verify new map image displays correctly"
echo "3. Check animation positioning matches the new map layout:"
echo "   - Red lines (500kV): Multiple diagonal lines"
echo "   - Blue lines (220kV): Vertical and angled lines"
echo "   - Purple lines (110kV): Curved and angled patterns"
echo "4. Ensure infrastructure labels are positioned correctly"
echo "5. Test on different screen sizes"
echo ""
echo "🚨 If animations don't align with map features:"
echo "   - Let me know which lines need repositioning"
echo "   - I can fine-tune the positioning percentages"